# Generated by Django 5.0.4 on 2024-12-20 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Hiredate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
